LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := Baidu_Location
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := $(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_PRIVILEGED_MODULE := true
LOCAL_MULTILIB := 32
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := liblocSDK6c
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES_32 := lib/armeabi-v7a/liblocSDK6c.so
LOCAL_SRC_FILES_64 := lib/arm64-v8a/liblocSDK6c.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX = .so
LOCAL_MULTILIB = both
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnetworklocation
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES_32 := lib/armeabi-v7a/libnetworklocation.so
LOCAL_SRC_FILES_64 := lib/arm64-v8a/libnetworklocation.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX = .so
LOCAL_MULTILIB = both
include $(BUILD_PREBUILT)

